from typing import Any, Literal

from pydantic import BaseModel, Field

ScopeType = Literal["all", "include", "exclude"]
SourceType = Literal["RI", "FRI"]


class Requirement(BaseModel):
    """Inventory-agnostic representation of a single timekeeping requirement.

    IDs are generated by the app (format: {SOURCE}-{PAYGROUP}-{SECTION_SLUG}-{NNN})
    and are never read from the source file.
    """

    id: str
    source: SourceType
    paygroup: str

    # Organisational structure
    section: str
    category: str | None = None  # FRI: Requirements Category; absent for RI

    # Content
    contract_reference: str | None = None
    description: str

    # Scope — the core field the analysis engine uses for set logic
    scope_type: ScopeType
    labor_agreements: list[str] = Field(default_factory=list)
    # Empty when scope_type == "all"; named codes when "include" or "exclude"

    # Configuration metadata
    hour_types: list[str] = Field(default_factory=list)
    earn_codes: list[str] = Field(default_factory=list)
    adj_earn_codes: list[str] = Field(default_factory=list)

    # Adapter-specific extras (sheet name, people group, notes, etc.)
    extra: dict[str, Any] = Field(default_factory=dict)

    def applies_to(self, target_las: set[str]) -> bool:
        """Return True if this requirement is in-scope for any of the target LAs."""
        if self.scope_type == "all":
            return True
        if self.scope_type == "include":
            return bool(target_las & set(self.labor_agreements))
        # exclude: in scope when the target is NOT in the exclusion list
        return bool(target_las - set(self.labor_agreements))